repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.6.1
    hooks:
    -   id: pre-commit-update
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.0
    hooks:
    -   id: ruff
        args: ["--fix", "--exit-non-zero-on-fix", "--ignore", "E501"]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
    -   id: ruff-format
-   repo: https://github.com/pycqa/pylint
    # Cannot be replaced by ruff until https://github.com/astral-sh/ruff/issues/970 is closed
    rev: "v3.3.5"
    hooks:
    -   id: pylint
        args: ['--rcfile=.pylintrc']
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.15.0"
    hooks:
    -   id: mypy
