apiVersion: v1
kind: Service
metadata:
  name: client-ui-streamlit
spec:
  type: LoadBalancer
  selector:
    app: client-ui-streamlit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501